/******************************************************************** ABOUT.H
 *                                                                          *
 *                       About Dialog definitions                           *
 *                                                                          *
 ****************************************************************************/

#ifndef ABOUT_H
#define ABOUT_H

extern FNWP AboutProcessor ;

#endif
